import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'translationStatus',
  title: 'Translation Management',
  type: 'document',
  icon: () => '🌐',
  groups: [
    { name: 'status', title: 'Translation Status' },
    { name: 'export', title: 'Export/Import' },
  ],
  fields: [
    defineField({
      name: 'contentType',
      title: 'Content Type',
      type: 'string',
      options: {
        list: [
          // Page Types
          { title: '📄 Page', value: 'page' },
          { title: '📝 Blog Post', value: 'post' },
          { title: '🛍️ Product Page', value: 'productPage' },
          { title: '👥 Membership Page', value: 'membershipPage' },
          { title: '🎯 Campaign', value: 'campaign' },

          // Product & Commerce
          { title: '📦 Product', value: 'product' },
          { title: '✨ Feature', value: 'feature' },
          { title: '📊 Social Proof', value: 'socialProof' },
          { title: '💎 Benefit', value: 'benefit' },
          { title: '📈 Stat', value: 'stat' },

          // Content & Media
          { title: '👤 Author', value: 'author' },
          { title: '🏷️ Tag', value: 'tag' },
          { title: '❓ FAQ Item', value: 'faqItem' },

          // Site Structure
          { title: '⚙️ Site Settings', value: 'siteSettings' },
        ],
      },
      group: 'status',
    }),

    defineField({
      name: 'contentReference',
      title: 'Content Item',
      type: 'reference',
      to: [
        // Page Types
        { type: 'page' },
        { type: 'post' },
        { type: 'productPage' },
        { type: 'membershipPage' },
        { type: 'campaign' },

        // Product & Commerce
        { type: 'product' },
        { type: 'feature' },
        { type: 'socialProof' },
        { type: 'benefit' },
        { type: 'stat' },

        // Content & Media
        { type: 'author' },
        { type: 'tag' },
        { type: 'faqItem' },

        // Site Structure
        { type: 'siteSettings' },
      ],
      group: 'status',
      validation: rule => rule.required(),
    }),

    defineField({
      name: 'priority',
      title: 'Translation Priority',
      type: 'string',
      options: {
        list: [
          { title: '🔴 Critical', value: 'critical' },
          { title: '🟡 High', value: 'high' },
          { title: '🟢 Medium', value: 'medium' },
          { title: '🔵 Low', value: 'low' },
        ],
      },
      group: 'status',
      initialValue: 'high',
    }),

    defineField({
      name: 'defaultTranslator',
      title: 'Default Translator',
      type: 'string',
      initialValue: 'Ismael Parra',
      group: 'status',
      options: {
        list: [
          'Ismael Parra',
          'Maria Rodriguez',
          'Klaus Mueller',
          'Yuki Tanaka',
          'Sophie Dubois',
        ],
      },
    }),

    defineField({
      name: 'autoGenerated',
      title: 'Auto-Generated Task',
      type: 'boolean',
      initialValue: false,
      group: 'status',
      description: 'Was this task created automatically?',
      hidden: ({ document }) => !document?._id,
    }),

    defineField({
      name: 'createdAt',
      title: 'Task Created',
      type: 'datetime',
      group: 'status',
      initialValue: () => new Date().toISOString(),
      readOnly: true,
    }),

    defineField({
      name: 'deadline',
      title: 'Translation Deadline',
      type: 'date',
      group: 'status',
      description: 'Target completion date for all languages',
      initialValue: () => {
        const date = new Date()
        date.setDate(date.getDate() + 7)
        return date.toISOString().split('T')[0]
      },
    }),

    defineField({
      name: 'estimatedWords',
      title: 'Estimated Word Count',
      type: 'number',
      group: 'status',
      description: 'Approximate word count for scope estimation',
    }),

    defineField({
      name: 'languages',
      title: 'Translation Progress',
      type: 'object',
      group: 'status',
      fields: [
        {
          name: 'german',
          title: 'German (DE)',
          type: 'object',
          fields: [
            {
              name: 'status',
              title: 'Status',
              type: 'string',
              options: {
                list: [
                  { title: '🔴 Not Started', value: 'not_started' },
                  { title: '🟡 In Progress', value: 'in_progress' },
                  { title: '🟢 Complete', value: 'complete' },
                  { title: '🔵 Needs Review', value: 'review' },
                ],
              },
            },
            { name: 'lastUpdated', title: 'Last Updated', type: 'datetime' },
            { name: 'translator', title: 'Translator', type: 'string' },
            {
              name: 'translationMethod',
              title: 'Translation Method',
              type: 'string',
              options: {
                list: [
                  { title: '👤 Manual Translation', value: 'manual' },
                  { title: '🤖 Sanity Assist (AI)', value: 'ai_assist' },
                  { title: '🔄 OpenAI API', value: 'openai_api' },
                  { title: '📝 Imported', value: 'imported' },
                ],
              },
              description: 'How was this translation created?',
            },
            {
              name: 'needsQA',
              title: 'Needs QA Review',
              type: 'boolean',
              initialValue: false,
              description:
                'Auto-flagged for AI translations. Check before marking complete.',
            },
          ],
        },
        {
          name: 'french',
          title: 'French (FR)',
          type: 'object',
          fields: [
            {
              name: 'status',
              title: 'Status',
              type: 'string',
              options: {
                list: [
                  { title: '🔴 Not Started', value: 'not_started' },
                  { title: '🟡 In Progress', value: 'in_progress' },
                  { title: '🟢 Complete', value: 'complete' },
                  { title: '🔵 Needs Review', value: 'review' },
                ],
              },
            },
            { name: 'lastUpdated', title: 'Last Updated', type: 'datetime' },
            { name: 'translator', title: 'Translator', type: 'string' },
            {
              name: 'translationMethod',
              title: 'Translation Method',
              type: 'string',
              options: {
                list: [
                  { title: '👤 Manual Translation', value: 'manual' },
                  { title: '🤖 Sanity Assist (AI)', value: 'ai_assist' },
                  { title: '🔄 OpenAI API', value: 'openai_api' },
                  { title: '📝 Imported', value: 'imported' },
                ],
              },
              description: 'How was this translation created?',
            },
            {
              name: 'needsQA',
              title: 'Needs QA Review',
              type: 'boolean',
              initialValue: false,
              description:
                'Auto-flagged for AI translations. Check before marking complete.',
            },
          ],
        },
        {
          name: 'spanish',
          title: 'Spanish (ES)',
          type: 'object',
          fields: [
            {
              name: 'status',
              title: 'Status',
              type: 'string',
              options: {
                list: [
                  { title: '🔴 Not Started', value: 'not_started' },
                  { title: '🟡 In Progress', value: 'in_progress' },
                  { title: '🟢 Complete', value: 'complete' },
                  { title: '🔵 Needs Review', value: 'review' },
                ],
              },
            },
            { name: 'lastUpdated', title: 'Last Updated', type: 'datetime' },
            { name: 'translator', title: 'Translator', type: 'string' },
            {
              name: 'translationMethod',
              title: 'Translation Method',
              type: 'string',
              options: {
                list: [
                  { title: '👤 Manual Translation', value: 'manual' },
                  { title: '🤖 Sanity Assist (AI)', value: 'ai_assist' },
                  { title: '🔄 OpenAI API', value: 'openai_api' },
                  { title: '📝 Imported', value: 'imported' },
                ],
              },
              description: 'How was this translation created?',
            },
            {
              name: 'needsQA',
              title: 'Needs QA Review',
              type: 'boolean',
              initialValue: false,
              description:
                'Auto-flagged for AI translations. Check before marking complete.',
            },
          ],
        },
        {
          name: 'japanese',
          title: 'Japanese (JP)',
          type: 'object',
          fields: [
            {
              name: 'status',
              title: 'Status',
              type: 'string',
              options: {
                list: [
                  { title: '🔴 Not Started', value: 'not_started' },
                  { title: '🟡 In Progress', value: 'in_progress' },
                  { title: '🟢 Complete', value: 'complete' },
                  { title: '🔵 Needs Review', value: 'review' },
                ],
              },
            },
            { name: 'lastUpdated', title: 'Last Updated', type: 'datetime' },
            { name: 'translator', title: 'Translator', type: 'string' },
          ],
        },
      ],
    }),

    defineField({
      name: 'automationLog',
      title: 'Automation Log',
      type: 'array',
      group: 'export',
      hidden: ({ document }) => !document?.autoGenerated,
      of: [
        {
          type: 'object',
          fields: [
            { name: 'action', title: 'Action', type: 'string' },
            { name: 'timestamp', title: 'Timestamp', type: 'datetime' },
            { name: 'details', title: 'Details', type: 'text', rows: 2 },
          ],
        },
      ],
    }),

    defineField({
      name: 'exportData',
      title: 'Export Package',
      type: 'text',
      group: 'export',
      description: 'JSON export of English content for translators',
      rows: 10,
    }),

    defineField({
      name: 'importInstructions',
      title: 'Import Instructions',
      type: 'text',
      group: 'export',
      initialValue: `1. Export English content using the button above
2. Send to translators 
3. Import translated content back to the source documents
4. Update translation status above`,
    }),
  ],

  preview: {
    select: {
      title: 'contentReference.title.en',
      type: 'contentType',
      germanStatus: 'languages.german.status',
      frenchStatus: 'languages.french.status',
    },
    prepare({ title, type, germanStatus, frenchStatus }) {
      const getStatusEmoji = (status: string) => {
        switch (status) {
          case 'complete':
            return '🟢'
          case 'in_progress':
            return '🟡'
          case 'review':
            return '🔵'
          default:
            return '🔴'
        }
      }

      const subtitle = `${type} | DE: ${getStatusEmoji(germanStatus)} | FR: ${getStatusEmoji(frenchStatus)}`
      return {
        title: title || 'Translation Item',
        subtitle,
      }
    },
  },
})
